services:
  postgres:
    image: postgres:16
    container_name: postgres_MR
    environment:
      POSTGRES_USER: meteorisk
      POSTGRES_PASSWORD: meteorisk_pw
      POSTGRES_DB: meteorisk_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  airflow:
    build: .
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://meteorisk:meteorisk_pw@postgres_MR:5432/meteorisk_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_HOME: /opt/airflow
      PYTHONPATH: /opt/airflow/MeteoRisk
      DB_HOST: postgres_MR
      DB_PORT: "5432"
      DB_USER: meteorisk
      DB_PASSWORD: meteorisk_pw
      DB_NAME: meteorisk_db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/MeteoRisk/logs
      - ./extraction:/opt/airflow/MeteoRisk/extraction
      - ./transformation:/opt/airflow/MeteoRisk/transformation
      - ./database:/opt/airflow/MeteoRisk/database
      - ./models:/opt/airflow/MeteoRisk/models
      - ./bronze:/opt/airflow/bronze
      - ./silver:/opt/airflow/MeteoRisk/silver
      - ./gold:/opt/airflow/MeteoRisk/gold
      - ./load:/opt/airflow/MeteoRisk/load
      - ./dashboard:/opt/airflow/MeteoRisk/dashboard
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username kerymy --password kerymy --firstname kerymy --lastname User --role Admin --email karimimoha0@gmail.com;
      airflow scheduler &
      exec airflow webserver -p 8080
      "
  streamlit:
    build: .
    container_name: streamlit
    depends_on:
      - postgres
    environment:
      PYTHONPATH: /opt/airflow/MeteoRisk
      DB_HOST: postgres_MR
      DB_PORT: "5432"
      DB_USER: meteorisk
      DB_PASSWORD: meteorisk_pw
      DB_NAME: meteorisk_db
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/opt/airflow/MeteoRisk/dashboard
      - ./database:/opt/airflow/MeteoRisk/database
      - ./models:/opt/airflow/MeteoRisk/models
    entrypoint: []
    command: streamlit run /opt/airflow/MeteoRisk/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
volumes:
  pgdata: