services:
  postgres:
    image: postgres:16
    container_name: postgres_MR
    environment:
      POSTGRES_USER: meteorisk
      POSTGRES_PASSWORD: meteorisk_pw
      POSTGRES_DB: meteorisk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    build: .
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://meteorisk:meteorisk_pw@postgres:5432/meteorisk_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com"
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://meteorisk:meteorisk_pw@postgres:5432/meteorisk_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: